#! /ysr/bin/env/ python3

from flask import Flask, request, render_template
import json
from teams_message import send_teams_message

DEBUG=True
app= Flask(__name__)
app.config['DEBUG'] = False

def process_webhook(webhook_dict):
    Web_hook_heading=("Organization: {0}, {1}, Network: {2}, {3}" .format(webhook_dict["organizationId"],webhook_dict["organizationName"],webhook_dict["networkName"], webhook_dict["networkId"]))
    Web_hook_cause=("Experienced a {0} Event at {1}".format(webhook_dict["alertType"],webhook_dict["occurredAt"]))
    Web_hook_more_info=("For more information {0} ".format(webhook_dict["organizationUrl"]))
    if DEBUG: print(Web_hook_heading)
    send_teams_message(Web_hook_heading)
    if DEBUG: print(Web_hook_cause)
    send_teams_message(Web_hook_cause)
    if DEBUG: print(Web_hook_more_info)
    send_teams_message(Web_hook_more_info)
    return "ok"

#Index url just pints a very basic Index.HTML
@app.route('/')
def index_url():
    return render_template("index.html")

@app.route('/meraki-webhooks', methods=['POST','GET'])
#This very sysple functiion intercepts webhooks generated by the Meraki dashboard and dumps out the JSON.
def meraki_webhooks():
    #Note that .json means that its already in a a dictionary.
    if DEBUG: print(dir(request))
    webhook_dict=request.json
    if DEBUG: print(json.dumps(webhook_dict, indent=4))
    #Do stuff with the Stuff that arrived via the HTTP POST
    if webhook_dict: process_webhook(webhook_dict)
    return 'ok'


# Run the Flask server on TCP port 5000
if __name__ == '__main__':
    app.run(host="0.0.0.0", port=5000)
# See PyCharm help at https://www.jetbrains.com/help/pycharm/
#Do stuff here to intialize webhooks.